language: php
php:
  - 7.0
  - 7.1
install:
  # Composer
  - rm -rf ./*
  - composer self-update
  - composer create-project bluzphp/skeleton --stability=dev
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  - cd skeleton
  # Require current module
  - composer require bluzphp/module-options:dev-master
  # Migrations
  - vendor/bin/phinx migrate -e default
  - vendor/bin/phinx seed:run
before_script:
  # Codeception
  - wget http://codeception.com/codecept.phar
script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # WebServer run
  - nohup bash -c "php -S 127.0.0.1:8000 -t ./public/ ./public/routing.php 2>&1 &" && sleep 1; cat nohup.out
  # CodeCeption
  - php codecept.phar run -g options
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
branches:
  only:
  - master
  - develop
