<?php /** @var \Application\Options\Row $row */ ?>
<?php $uid = uniqid('form_', false); ?>
<form id="<?=$uid?>" action="<?=$this->url('options', 'crud')?>" class="form-horizontal ajax" method="POST">
    <input type="hidden" name="_method" value="<?=$method?>"/>
    <?php if ($method !== 'POST') : ?>
        <input type="hidden" name="namespace" value="<?=esc($row->namespace)?:'default'?>"/>
        <input type="hidden" name="key" value="<?=esc($row->key)?>"/>
    <?php endif; ?>
    <div class="modal-header">
      <h4 class="modal-title"><?=__('Options')?></h4>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
        <?php if ($method === 'PUT') :?>
        <div class="form-group row">
            <label class="control-label col-lg-4" for="author"><?=__('Author')?></label>
            <div class="col-lg-8">
                <input type="text" class="form-control" id="author" name="author" value="<?=\Application\Users\Table::findRow($row->userId)->login;?>" disabled />
            </div>
        </div>
        <?php endif; ?>
        <div class="form-group row">
            <label class="control-label col-lg-4" for="namespace"><?=__('Namespace')?></label>
            <div class="col-lg-8">
                <input type="text" class="form-control" id="namespace" name="namespace" value="<?=esc($row->namespace)?:'default'?>" <?=($method !== 'POST')?'disabled':''?> required />
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-lg-4" for="key"><?=__('Key name')?></label>
            <div class="col-lg-8">
                <input type="text" class="form-control" id="key" name="key" value="<?=esc($row->key)?>" <?=($method !== 'POST')?'disabled':''?> />
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-lg-4" for="value"><?=__('Key value')?></label>
            <div class="col-lg-8">
                <?php $value = $row->value; ?>
                <?php if (is_array($value)) : ?>
                <input type="text" class="form-control" id="value" name="value" disabled value="<?=__('Array (length=%d)', count($value));?>"/>
                <?php elseif (is_object($value)): ?>
                <input type="text" class="form-control" id="value" name="value" disabled value="<?=__('Object of `%s` class', get_class($value));?>"/>
                <?php else: ?>
                <input type="text" class="form-control" id="value" name="value" value="<?=esc($row->value)?>" />
                <?php endif; ?>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-12">
            <label class="control-label" for="description"><?=__('Description')?></label>
            <textarea class="form-control" id="description" name="description"><?=esc($row->description)?></textarea>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
    </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>